### PR TITLE
<content> select should only match children.

### LINKED ISSUE #786: <content> select should only select children
Nested components using multiple insertion points with select do not work properly, because the first level component's select selects the elements that are inside the nested component: http://jsfiddle.net/nkovacs/g0oq6xf8/3/

According to [this](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom/#toc-projection), select can only select elements which are immediate children of the host node. This is how it should work: http://jsfiddle.net/nkovacs/g0oq6xf8/2/

### PR DESCRIPTION
**Pull request by nkovacs**
Fixes #786

### CODE REVIEW

File: src/compiler/transclude.js [hunk 1]
```diff
@@ -87,11 +87,13 @@ function transcludeContent (el, raw) {
       select = outlet.getAttribute('select')
       if (select) {  // select content
         selected = raw.querySelectorAll(select)
-        outlet.content = _.toArray(
-          selected.length
-            ? selected
-            : outlet.childNodes
-        )
+        if (selected.length) {
```
Comment (yyx990803) [inline src/compiler/transclude.js]: One possible issue here: if all nodes in `selected` are nested ones (thus should be filtered out), we end up outputting empty content, but in that case we should actually use the fallback content (`outlet.childNodes`).

According to http://w3c.github.io/webcomponents/spec/shadow/#dfn-pool-distribution-algorithm, the algorithm here should be:

- For each direct child nodes of `raw`, check if it matches `select`.
- If yes, push it into `selected`.
- If `selected` ends up empty, use `outlet.childNodes` instead.

This also means we need a `matches()` helper in `util/dom.js`:

``` js
  var p = Element.prototype
	var matches = p.matches || p.webkitMatchesSelector || p.mozMatchesSelector || p.msMatchesSelector
  exports.matches = function (el, selector) {
    return matches.call(el, selector)
  }
```

Comment (nkovacs) [inline src/compiler/transclude.js]: I wanted to avoid element.matches because its browser support is slightly worse than querySelectorAll (http://caniuse.com/#feat=matchesselector vs http://caniuse.com/#search=queryselectorall). In practice it probably doesn't matter (opera mini 8 is the only browser that's still used of those, and I don't know if vue even supports it), but I decided to play it safe.

**Comment by yyx990803** [comment]
Thanks!
